# Generated by Django 4.0.6 on 2022-08-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aesk_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('alt_email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('alt_phone', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('aesk_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.member')),
                ('employment_status', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('business_sector', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
